apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "metrics-operator.fullname" . }}-server-resources
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "metrics-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
