apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: hello-keptn-upstream-parent
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/keptn/lifecycle-controller/main/examples/taskonly-hello-keptn/http/hello-keptn.ts
parameters:
    map:
      name: "Parent Developer"

