apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  namespace: podtato-kubectl
  name: pre-deployment-hello
  namespace: podtato-kubectl
spec:
  function:
    inline:
      code: |
        console.log("Pre-Deployment Task has been executed");
