namespace: keptn-lifecycle-toolkit-system
resources:
- base/deployment.yaml
- base/rbac.yaml
- base/serviceaccount.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - base/scheduler-config.yaml
  name: scheduler-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: image
  newName: ghcr.io/keptn/scheduler
  newTag: "202211041667586936"
- name: klfc-scheduler
  newName: docker.io/thschue/scheduler
  newTag: "202211151668508663"
- name: scheduler
  newName: docker.io/thschue/scheduler
  newTag: "202211151668508663"
