name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  GO_VERSION: "1.18"
  CONTROLLER_TOOLS_VERSION: "v0.9.2"
  SCHEDULER_COMPATIBLE_K8S_VERSION: "v0.24.3"

jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main

  build-release:
    if: needs.release-please.outputs.releases_created == 'true'
    needs:
      - release-please
    strategy:
      matrix:
        config:
          - name: "keptn-lifecycle-controller"
            folder: "operator/"
          - name: "scheduler"
            folder: "scheduler/"
          - name: "functions-runtime"
            folder: "functions-runtime/"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    env:
      IMAGE_TAG: ghcr.io/keptn/${{ matrix.config.name }}:${{ needs.release-please.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v2.8.1

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.config.folder }}
          platforms: linux/amd64,linux/arm64
          target: production
          tags: |
            ${{ env.IMAGE_TAG }}
          build-args: |
            GIT_HASH=${{ env.GIT_SHA }}
            RELEASE_VERSION=dev-${{ env.DATETIME }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            CONTROLLER_TOOLS_VERSION=${{ env.CONTROLLER_TOOLS_VERSION }}
            SCHEDULER_COMPATIBLE_K8S_VERSION=${{ env.SCHEDULER_COMPATIBLE_K8S_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Sign container images
        env:
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign ${{ env.IMAGE_TAG }}

  release-manifests:
    if: needs.release-please.outputs.releases_created == 'true'
    needs:
      - release-please
      - build-release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create manifests
        env:
          TAG: ${{ needs.release-please.outputs.tag_name }}
        run: |
          cd scheduler
          make release-manifests
          cd ../operator
          make controller-gen release-manifests
          cd ..
          echo "---" >> operator/config/rendered/release.yaml
          cat operator/config/rendered/release.yaml scheduler/config/rendered/release.yaml > manifest.yaml

      - name: Attach release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: manifest.yaml
