name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Run release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          config-file: ./release-please-config.json

  build-release:
    if: needs.release-please.outputs.releases_created == 'true'
    needs:
      - release-please
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create images and manifests
        run: |
          cd functions-runtime
          make build-and-push-image TAG=${{ needs.release-please.outputs.tag_name }}
          cd ../scheduler
          go mod tidy
          make build-and-push-image TAG=${{ needs.release-please.outputs.tag_name }}
          make release-manifests TAG=${{ needs.release-please.outputs.tag_name }}
          cd ../operator
          go mod tidy
          make build-and-push-image TAG=${{ needs.release-please.outputs.tag_name }}
          make controller-gen release-manifests TAG=${{ needs.release-please.outputs.tag_name }}
          cd ..
          echo "---" >> operator/config/rendered/release.yaml
          cat operator/config/rendered/release.yaml scheduler/config/rendered/release.yaml > manifest.yaml

      - name: Attach release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: manifest.yaml
